[${trunk}]
type=registration
transport=transport-udp
outbound_auth=${trunk}_auth
server_uri=sip:${server}:5060
client_uri=sip:${username}@${server}:5060
retry_interval=60
expiration=120
contact_user=${username}

[${trunk}_auth]
type=auth
auth_type=userpass
password=${password}
username=${username}

[${trunk}]
type=aor
contact=sip:${server}:5060

[${trunk}]
type=endpoint
context=from-pstn
disallow=all
allow=ulaw,alaw
auth=${trunk}_auth
outbound_auth=${trunk}_auth
aors=${trunk}
from_user=${username}
from_domain=${server}
direct_media=no

[${trunk}]
type=identify
endpoint=${trunk}
match=${server}
