[${name}]
type=registration
transport=transport-udp
outbound_auth=${name}_auth
server_uri=sip:${server}:5060
client_uri=sip:${username}@${server}:5060
retry_interval=60
expiration=120
contact_user=${username}

[${name}_auth]
type=auth
auth_type=userpass
password=${password}
username=${username}

[${name}]
type=aor
contact=sip:${server}:5060

[${name}]
type=endpoint
context=from-pstn
disallow=all
allow=ulaw,alaw
auth=${name}_auth
outbound_auth=${name}_auth
aors=${name}
from_user=${username}
from_domain=${server}
direct_media=no

[${name}]
type=identify
endpoint=${name}
match=${server}
